title: "My GitHub Pages Portfolio"
description: "A portfolio showcasing my coding projects."
baseurl: "" # Leave blank for user/organization GitHub Pages
url: "https://rrrbbb1.github.io" # Replace with your GitHub Pages URL
theme: minima # GitHub-supported Jekyll theme